spring.application.name=pos-system-backend
spring.datasource.url=jdbc:postgresql://db.foferwxrzvhgorgkllsu.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=weehenapos12

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connection Pool Settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000

# Logging
logging.level.root=INFO
logging.level.com.pos.pos_system_backend=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE